### ISSUE TITLE
Player hangs when moving to next song on Yosemite

### ISSUE THREAD

**Issue by robertotremonti** [kbhomes/radiant-player-mac#227]
When Radiant Player automatically moves to next songs on Yosemite, it hangs for 10/15 seconds before starting to play.

**Comment by ploum** [comment]
I can confirm this issue with no custom theme, no notification or anything fancy. I've also tested with the HTML5 player enabled/disabled without any difference.

Well, it seems that with the flash player, the bug happens less.

**Comment by kbhomes** [comment]
This performance issue should be solved in 1.3.2. The fix involves multiple performance fixes related to the mini player, as well as asynchronous loading of the album art in the notifications (previously, the album art was downloaded synchronously so the app would hang while it was downloading).
