### ISSUE TITLE
"Spotify Black" Theme Styling Off

### ISSUE THREAD

**Issue by ryanmoorman** [kbhomes/radiant-player-mac#271]
There are some issues with the styling of the "Spotify Black" theme in the latest update. It is impossible to perform some functionalities because certain elements are the same color as the background. 

![screen shot 2014-12-10 at 3 43 49 pm](https://cloud.githubusercontent.com/assets/5170196/5383935/73fc2efe-8083-11e4-9ed8-c0124554e3b6.png)
![screen shot 2014-12-10 at 3 44 55 pm](https://cloud.githubusercontent.com/assets/5170196/5383943/857b993a-8083-11e4-9695-57bf68c54207.png)

**Comment by tonybaroneee** [comment]
I fixed this with https://github.com/kbhomes/radiant-player-mac/pull/263 but he didn't cut a release yet :(

**Comment by kbhomes** [comment]
As @tonybaroneee said, this was fixed in #263 and will be coming out very, very soon.
