### ISSUE TITLE
How to open Developer Tools?

### ISSUE THREAD

**Issue by FezVrasta** [kbhomes/radiant-player-mac#278]
I would like to customize the Yosemite theme to better fit my needs but I can't find a way to open developers tools on this software.

Pressing <kbd>CMD</kbd>+<kbd>OPTION</kbd>+<kbd>I</kbd> doesn't open them. Any advice?

**Comment by kbhomes** [comment]
You can open developer tools by right clicking somewhere on the page and clicking "Inspect Element".

**Comment by FezVrasta** [comment]
![image](https://cloud.githubusercontent.com/assets/5382443/6996802/17acd3fc-db9f-11e4-8398-e131fbd4da6f.png)

What am I doing wrong?

**Comment by kbhomes** [comment]
Try running this command in Terminal, and then trying again:

    defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

**Comment by FezVrasta** [comment]
yes with it it works!

maybe would be a good thing write it in the README...
