### ISSUE TITLE
Player stops playing sometimes

### ISSUE THREAD

**Issue by daften** [kbhomes/radiant-player-mac#281]
@random, from then on until a while later, anything beyond that point in that song, can't be skipped too, it just doesn't continue.

**Comment by abarisain** [comment]
This happens in Safari and Chrome for me too, so I think it's more of a Google problem

**Comment by daften** [comment]
i've only noticed this in safari, not in chrome myself, but it could be. I think it has something to do with the flash player in safari.

**Comment by kbhomes** [comment]
This may have been related to performance issues in 1.3.1, though if you noticed it also happening in Safari, then it is likely out of my control unfortunately. Upgrading to 1.3.2 may be worth a shot, however.
