### ISSUE TITLE
Nightly or "Edge" builds?

### ISSUE THREAD

**Issue by intel352** [kbhomes/radiant-player-mac#286]
Is there a way to set up an automated build process that builds nightly or weekly? It would be nice to get updated builds easily to preview new fixes/features...  Ideally integrated into the auto-update process (so you'd change what channel you update from)

**Comment by lyndsysimon** [comment]
I just cloned the repo and built it in XCode - it worked.

I'd never built anything in XCode before, but it's pretty easy. Shoot me an email if you need help?

**Comment by intel352** [comment]
It's easy enough to build in XCode, but then if you want multiple machines
using the latest build, you can't simply distribute your custom build, you
instead have to properly package and codesign the app. Getting codesigning
to behave correctly so then you can send the app to other machines, and
actually install without erroring due to signature, isn't wholly
straightforward.

Plus, then you have to make a point of monitoring the project manually, to
then create your own builds.

This is all what I'm doing now, but I'd much rather see a "nightly build"
channel, so that I can automatically get notified up updates, have the
update automatically downloaded/installed.
