### ISSUE TITLE
Add ability to use the F7/8/9 keys 

### ISSUE THREAD

**Issue by leecarlton** [kbhomes/radiant-player-mac#287]
Hi, 

Is it possible to add the ability to use the F7/8/9 keys as you would in iTunes, even when the App is not currently highlighted? This would be useful for skipping to the next song without having to toggle to the app.

**Comment by tthayer** [comment]
There is a setting for using the media keys. I had to enable the "Alternate method" checkbox on my system.

**Comment by kbhomes** [comment]
@leecarlton, the media keys in F7/F8/F9 (previous, play/pause, next) should work out of the box. They're working for me even when the app isn't the currently focused app. If it's not working for you, try running Radiant Player when there isn't a competing application (like iTunes or Spotify) running and see if it works. If not, also try the "Alternate method" in the Advanced preferences.

**Comment by leecarlton** [comment]
I got them with the alternative method. Thanks!

**Comment by krisdestruction** [comment]
Can this issue be closed if the OP has it working?
