### ISSUE TITLE
Blocked Plugin - after latest Mac Security Update

### ISSUE THREAD

**Issue by sean8781** [kbhomes/radiant-player-mac#293]
After installing Security Update 2015-003 the app opens with a message "Blocked Plugin" and the app is unable to access Google Play.

**Comment by mattcaffeine** [comment]
You need to update flash-player on your mac.

**Comment by sean8781** [comment]
thank you, that makes sense.. is there any way to detect that and provide a
message when Radiant Player is launched?  Or maybe put that in a FAQ?

**Comment by kbhomes** [comment]
Good news, this issue was fixed in #258, so a message will now pop up when the plugin is blocked.
