### ISSUE TITLE
Version 1.3.2 crashing on startup

### ISSUE THREAD

**Issue by ccampbell** [kbhomes/radiant-player-mac#294]
I don't know if this might be related to the fact that I was using a beta version before updating, but version 1.3.2 crashes on launch for me on OS 10.9.5.  Are there some preference files I need to remove?

Crash log is here:
https://gist.github.com/ccampbell/fb2279c86feb6325c823

**Comment by kbhomes** [comment]
What a major oversight! I didn't realize the method I used was introduced in 10.10. This is now fixed in 563c57d and will be pushed out very shortly.

**Comment by ccampbell** [comment]
Thank you!

**Comment by kbhomes** [comment]
And now version 1.3.3 is out!

**Comment by rmkbow** [comment]
1.3.3 crashes on me. Could it be because I'm on 10.8.5?

**Comment by brandiquintos** [comment]
Same issue for me, and I'm on 10.8.5 as well.

**Comment by kbhomes** [comment]
I believe it is 10.8 related, I will try to look into this as soon as I can.

**Comment by uzudil** [comment]
+1
