### ISSUE TITLE
Mini player displays when switching spaces

### ISSUE THREAD

**Issue by ryanproud** [kbhomes/radiant-player-mac#300]
I upgraded to 1.3.3 today and now when I switch between spaces the mini player displays momentarily.

**Comment by shawn-mitch** [comment]
I've also had this issue, but it was only with the prerelease until 1.3.3. Here is a video of this occurring: https://docs.google.com/file/d/0ByW7WzYRBoRRX24zUkstVmV1T0E/edit?usp=drivesdk

**Comment by almozavr** [comment]
Got the same issue: it occurs after the very first click on statusbar icon (after first mini-player show up).

**Comment by kbhomes** [comment]
This issue has been fixed in 1682054 (see issue #309).
