### ISSUE TITLE
Add class to body when window is not active

### ISSUE THREAD

**Issue by FezVrasta** [kbhomes/radiant-player-mac#304]
I think it would be helpful tu add a class when the window is not active (not on focus) so that we can style the content according (making the app look like the native Yosemite apps with two states header etc).

Is it possible?

**Comment by nielstholenaar** [comment]
This has already been implemented. When the window becomes inactive the `inactive` class will be set on the `body` element.

```
Callbacks: {
    onEnterFullScreen: function() { },
    onExitFullScreen: function() { },
    onWindowDidBecomeActive: function() {
        document.body.classList.remove('inactive');
     },
     onWindowDidBecomeInactive: function() {
         document.body.classList.add('inactive');
     },
}
```
 See line 45 to 54 of [radiant-player-mac/js/styles.js](https://github.com/kbhomes/radiant-player-mac/blob/master/radiant-player-mac/js/styles.js)

**Comment by FezVrasta** [comment]
Ah yes thanks! I didn't noticed it.
