### ISSUE TITLE
Crash Immediately on Startup

### ISSUE THREAD

**Issue by mrwizard65** [kbhomes/radiant-player-mac#305]
OS 10.8.5

**Comment by slayer925** [comment]
Same here, same OS version, last flash version installed. [Here is the log](http://pastebin.com/073BPWzE)

**Comment by hoverkraft** [comment]
Happpens here too, 10.8.5

**Comment by ggrell** [comment]
Tried upgrading because it just showed blank screen after a Flash updated. Now with 1.3.3, it just crashes on launch (OS X 10.8.5)

**Comment by kbhomes** [comment]
Closing this issue, since I'm designating the main issue for 10.8 support to be #291.
