### ISSUE TITLE
Mini-Player Popup when Switching Spaces

### ISSUE THREAD

**Issue by krisdestruction** [kbhomes/radiant-player-mac#309]
The miniplayer in the status bar pops up while switching spaces.
Version: 1.3.3

While switching spaces. The mini-player was not previously open in the status bar. This occurs when the application is and isn't in full screen.
![screen shot 2015-04-27 at 7 41 50 pm](https://cloud.githubusercontent.com/assets/1440068/7360210/d7b1aab0-ed15-11e4-9b1d-8692047528bd.png)

After the space is switched without any input.
![screen shot 2015-04-27 at 7 41 57 pm](https://cloud.githubusercontent.com/assets/1440068/7360212/d8aa7c76-ed15-11e4-9252-6ac4718d1c09.png)

**Comment by shadownnc** [comment]
I'm also able to reproduce this issue.

**Comment by kbhomes** [comment]
I could confirm this issue as well, and with the most recent code change it should no longer be a problem.
