### ISSUE TITLE
Rating doesn't hide, can't read title

### ISSUE THREAD

**Issue by Lotuashvili** [kbhomes/radiant-player-mac#312]
I can't hide rating.

![screen shot 2015-05-02 at 1 13 37](https://cloud.githubusercontent.com/assets/6238393/7440526/5cfed5ee-f0cc-11e4-9b47-ed76403169e3.png)
![screen shot 2015-05-02 at 1 13 47](https://cloud.githubusercontent.com/assets/6238393/7440525/5cfe06f0-f0cc-11e4-9883-6214f9d5b40e.png)

**Comment by kbhomes** [comment]
This seems to have been a bug that was introduced, but I can't fix it as it doesn't apply anymore, as they removed the star ratings feature from Google Play Music itself.
