### ISSUE TITLE
"Select All" hotkey not implemented

### ISSUE THREAD

**Issue by mttmllns** [kbhomes/radiant-player-mac#317]
When using the search field the cmd+a "Select All" hotkey doesn't work. I never realized how much I use this to clear the field before searching again.

**Comment by jywll** [comment]
I'm here looking for the new beta, to fix the new issues but this small tick has bothered me before. Just commenting to confirm select all would be great

**Comment by mttmllns** [comment]
Works like a charm!  Many thanks!
