### ISSUE TITLE
Songs don't load with Google's new UI

### ISSUE THREAD

**Issue by ollien** [kbhomes/radiant-player-mac#321]
#318 exists, but that specifically regards the UI. There should be a separate issue regarding songs not loading.

Songs simply just continuously load when played, with the below icon continuously spinning.

![Icon](https://cloud.githubusercontent.com/assets/977151/7643941/236daba8-fa6c-11e4-9f7e-c72fd4f83fa9.png)

**Comment by ncolomer** [comment]
I can confirm the issue on MacOS 10.10.3.
Songs won't load (spinning continuously) and software blocks after a while (spinning MacOS mouse pointer) until I kill it.

**Comment by CKrawczyk** [comment]
I am also see thing problem on OSX 10.10.3

**Comment by rickarubio** [comment]
also on 10.10.3 and having same issue

**Comment by mcg** [comment]
Similar issue on other WebKit based wrappers.
https://github.com/tiliado/nuvolaplayer/issues/100

**Comment by pdonorio** [comment]
+1 checked today, can't play with new ui on 10.10.3

**Comment by hackur** [comment]
+1 using 10.10.3

**Comment by mfkp** [comment]
+1 on 10.9.5 v1.3.3

I'll donate some more money if this gets fixed, I use this app every day!

**Comment by ewa4618** [comment]
Same comment to #318 

1. Access Google Play Music with using web browser
2. Go to Settings > Labs
3. Turn "HTML 5 Audio" ON
4. Run Radiant Player, and you should be able to load/play songs

**Comment by twolfson** [comment]
I have written an Electron wrapper around Google Music with media key bindings that supports this latest Google Music redesign. It is not as fully featured as Radiant but it does work.

https://github.com/twolfson/google-music-electron

**Comment by ncolomer** [comment]
@ewa4618's comment did the trick!
Just go to https://play.google.com/music/listen#/accountsettings and activate "HTML 5 Audio" as said.

**Comment by ollien** [comment]
@ewa4618 No dice. I've had HTML5 Audio on for a long time. :/

**Comment by pdonorio** [comment]
> @ewa4618's comment did the trick!

Not for me

**Comment by dlhextall** [comment]
>Same comment to #318
>
>Access Google Play Music with using web browser
>Go to Settings > Labs
>Turn "HTML 5 Audio" ON
>Run Radiant Player, and you should be able to load/play songs

Already had it enabled and music still won't play.

**Comment by jawtab** [comment]
Same issue here.  I went to "check out" the new google play experience in Safari and ever since it has been acting up.  

Cannot play & weird white box on bottom left corner.

I tried learning cache and cookies.  no luck either.
![radiant_player_and_thumbs_up_-_google_play_music](https://cloud.githubusercontent.com/assets/12490007/7674127/12c79388-fcef-11e4-9adb-3557beca34a5.jpg)

**Comment by CKrawczyk** [comment]
Switching to HTML5 audio worked for me, songs now play just fine.

**Comment by RickWong** [comment]
@jawtab That thing seems to be an embedded Adobe Flash object.

**Comment by jonlyons** [comment]
I had HTML5 audio already toggled on. Toggled it off then back on, songs still don't play for me.

I also have the same issue as @jawtab with the white box in the bottom left corner.

**Comment by jawtab** [comment]
great work around by Hutchy!

https://github.com/hutchy2570/GoogleMusicKeys/releases/tag/2015-05-18

**Comment by rlschroeder** [comment]
Same issue. Enabling HTML 5 didn't work.

**Comment by Mitchlol** [comment]
app is literally 10/10 dead.

**Comment by colby-swandale** [comment]
Hey Guys, this is going to sound like a shameless plug, and it probably is. until radiant is back to normal i  have quickly whipped up a repo built on electron that has the media controls for google play music.

https://github.com/colby-swandale/honeybird

Thanks.

**Comment by gholts** [comment]
Trying out @colby-swandale's app just cause I'm too lazy to try work arounds.

**Comment by svebk** [comment]
That worked for me. 
Close Radiant. Go to https://play.google.com/music/listen?u=0#/accountsettings, activate Audio HTML5, save, click on refresh library cache (or sthg like this). Launch Radiant. Audio works and no more weird white box at the bottom left.

**Comment by arboleya** [comment]
@twolfson Awesome initiative, however tray icon and mediakeys doesn't work on OSX (is it windows only?).

@colby-swandale Gorgeous stuff for plain 45mins, thanks.

@jawtab Hutchy's GooglerMusicKeys worked fine as well.

**Comment by twolfson** [comment]
@arboleya `google-music-electron` should be cross platform. Can you open an issue on the repo so we can discuss it without cluttering this thread? 

https://github.com/twolfson/google-music-electron/issues/new

**Comment by warb2n** [comment]
ye new version very bad + all separate. And media buttons don't work.
And how download 1.3.3.1-beta ? When i try always download 1.3.3 =@

**Comment by NoelLH** [comment]
@warb2n Try [here](https://github.com/kbhomes/radiant-player-mac/releases/download/v1.3.3.1-beta/Radiant.Player.zip)

Working for me on 10.10.3, thanks!

**Comment by ollien** [comment]
New beta seems to have fixed things!

@kbhomes you are the man! I'll leave this issue open in case you want to close it yourself.

**Comment by kbhomes** [comment]
Glad to hear it's working! Full release should be out soon.

**Comment by jawtab** [comment]
@kbhomes Sajid is the man!  Thanks for the speedy fix on the beta!!!  Looks good on 10.10.3 here.

**Comment by moeffju** [comment]
Side note: If I have the beta channel selected, the download link still takes me to the normal download page where the beta is not linked. Opening https://github.com/kbhomes/radiant-player-mac/releases would be more sensible?
