### ISSUE TITLE
No integration works in Mac OS X 10.10.2

### ISSUE THREAD

**Issue by sandrotosi** [kbhomes/radiant-player-mac#322]
Hello,
I just installed 1.3.3 on my os x 10.10.2 and basically no integration with the os works:

- the media key do not play/pause or fwd/rwd
- no notification
- the mini player in the top bar says "no song currently playing" while I'm listening to music instead
- using the control from the dock app dont work
- same goes with the control in the top bar when the player in foreground, no action
- the player layout looks completely different than the screenshot on the website (it looks like it is just the webpage shown in the app)

the only thing that works to control the player is thru the embedded player when the app is open.

what's going on? :(

**Comment by vitch** [comment]
Same for me with with `1.3.3` on OSX `10.10.3` since I upgraded from Mavericks.

Additionally the minify etc buttons sit on top of the text / navigation:

![screen shot 2015-05-21 at 18 12 56](https://cloud.githubusercontent.com/assets/9898/7754507/0833e626-ffe5-11e4-843a-d401d6b2ad4b.png)

**Comment by thornycrackers** [comment]
I also have this issue with 1.3.1 on 10.10.3

**Comment by ericssimon1** [comment]
I've got the same problem. Showing "No song currently playing" in the menu bar despite a song being played. 

Moreover, AppleScript support seems to be nonfunctional, presumably related to the same original issue. 
The 'player state' is always 0 regardless of whether a song is playing or not.

![image](https://cloud.githubusercontent.com/assets/4022716/7775239/6503aa90-007f-11e5-9929-e882ec19645f.png)

**Comment by ericssimon1** [comment]
The latest Radiant Player beta (1.3.3.1-beta) fixes all of these issues for me:

https://github.com/kbhomes/radiant-player-mac/releases/tag/v1.3.3.1-beta

**Comment by vitch** [comment]
Me too! Thanks @ericssimon1 - I think this issue can be closed :smile:

**Comment by sandrotosi** [comment]
this issue can be closed when there will be a stable release with the fixes

**Comment by kdaniels** [comment]
I had these issues, confirmed that 1.3.3.1-beta fixed them for me as well (10.9.5).
