### ISSUE TITLE
[OS X 10.9] Queue does not display

### ISSUE THREAD

**Issue by InnocentEd** [kbhomes/radiant-player-mac#323]
When playing a radio station the "playlist" button displays a white triangle but no way to view the current playlist

**Comment by tgerulaitis** [comment]
It happens when playing normal playlists or albums too. The queue pop up does not display.

Radian Player v1.3.3.1-beta
OS X v10.9.5

![screen shot 2015-05-27 at 10 22 14 2](https://cloud.githubusercontent.com/assets/613076/7832880/457f929a-045a-11e5-8c6d-6afc3a3c49a8.png)

**Comment by kbhomes** [comment]
This appears to be a problem with the version of WebKit that is used in Mac OS X 10.9. Please let me know if the issue also appears in Safari for you. 

However! I believe that the OS X system updates such as the 10.9.5 update do change Safari to use the latest version of WebKit, but they *do not* update the system's version of WebKit -- meaning that Radiant Player is forced to keep using the older, incompatible browser engine. I've had this happen to me on my OS X 10.8.5 machine, and I think this would explain why Google Play Music works in Safari for many users while not working in Radiant Player.

If the queue button does work for you in Safari, but does not in Radiant Player, then I believe that it will be unfortunately not possible to get the queue button working unless you upgrade to a newer OS, like 10.10, that has an updated system WebKit.

Please let me know!

**Comment by nashbridges** [comment]
Queue pop up works well in Safari, OS X 10.9.5

**Comment by afunix** [comment]
Mac OS X 10.9.5
Safari 7.1.6 (9537.85.15.3) shows queue correctly
Radiant Player 1.3.3.2-beta shows white vertical line and a triangle instead of queue.

**Comment by kbhomes** [comment]
I actually diagnosed this more easily than I had thought, with a decent workaround. The bug exists because the WebKit in Mac OS X 10.9 doesn't correctly support viewpoint units inside `-webkit-calc()`, so I approximated using `top`.

It actually seems to work correctly on Mavericks as it does on Yosemite.
