### ISSUE TITLE
It's over. Confirmed broken on all my macs. :(

### ISSUE THREAD

**Issue by mpsulli** [kbhomes/radiant-player-mac#324]
Not sure what's going on but I can't get it to work on either of my macs. Looks like others have already mentioned some of the problems in other issues (blank space in UI, song loading forever that doesn't play) but I figured I'd start this thread and see if it's fully broken for others. I tried the HTML5 fix but no luck.

Would love to see this take the direction MailPlane took and become a big boy paid app in the app store with full support.

**Comment by hught78** [comment]
Downloading the most recent beta fixed these issues (among others) on my Mac. 
https://github.com/kbhomes/radiant-player-mac/releases/tag/v1.3.3.1-beta

**Comment by FilSalustri** [comment]
Ditto for me.  On 20 May, Remote Desktop Client was updated (for Yosemite).  After that, I got all the same problems that mpsulli did.
Fortunately, the 1.3.3.1beta seems to fix it.

**Comment by aaronbwcollins** [comment]
Finally! Beta release fixed my current favorite app.

**Comment by mpsulli** [comment]
Thank you all for sharing the good news about the beta. Cheers to everyone
that's working on this project.

**Comment by mrThe** [comment]
:+1:

**Comment by infamousv** [comment]
Thanks you to all that made this happen / worked on it. Without this app I was thinking about cancelling my subscription, but alas it works again thanks again to all the people working on / supporting  this project!

**Comment by davidharrison92** [comment]
Thanks for this release. Having to use that Chrome mini-player was killing me.

**Comment by aequitas** [comment]
Works for me to, running 10.10.4 (14E26a)

**Comment by donlion** [comment]
Wohoo!
Working on MacBook Pro (Retina, 13-inch, Late 2013) OS X 10.10.3

**Comment by danilogcarolino** [comment]
Thanks! :-D
