### ISSUE TITLE
[1.3.3.2 beta] Dark Theme menu title color is dark when it should be light

### ISSUE THREAD

**Issue by joeljfischer** [kbhomes/radiant-player-mac#329]
In the latest betas, when going into the menu for an album, for instance by right clicking on an album, then going into "add album to playlist", there are section headers for "Recent" and "All". These section headers are black on dark gray, they should be white.

**Comment by kbhomes** [comment]
Good catch, I don't have many playlists so these menu headers never appeared for me until I tested them just now.
