### ISSUE TITLE
[1.3.3.2 beta] Bad background for playlists in dark mode

### ISSUE THREAD

**Issue by jywll** [kbhomes/radiant-player-mac#330]
See attached, showing white bg with white/gray text 

![screen shot 2015-06-03 at 4 13 05 pm](https://cloud.githubusercontent.com/assets/8052885/7973543/71279c88-0a0b-11e5-88c6-7671dfb07fbf.png)

**Comment by kbhomes** [comment]
Can you let me know which version of OS X you're using?

**Comment by jywll** [comment]
10.10.3

**Comment by jywll** [comment]
album pages are worse 
![screen shot 2015-06-03 at 4 30 33 pm](https://cloud.githubusercontent.com/assets/8052885/7973754/ea30acee-0a0d-11e5-946d-3fe64e12b0cc.png)

**Comment by jywll** [comment]
thanks

**Comment by morganhi** [comment]
Same here, the bar animation for current playing track is working though.
![screen shot 2015-06-03 at 21 57 40](https://cloud.githubusercontent.com/assets/1334245/7974733/cab56aac-0a3b-11e5-815d-362e4950e1ee.png)

**Comment by kbhomes** [comment]
Very strange, this was certainly not the case yesterday, Google may have updated their stylesheets. In any case, this is now fixed.

**Comment by morganhi** [comment]
Looks great, thanks.
