### ISSUE TITLE
Skips every song.

### ISSUE THREAD

**Issue by sambass1** [kbhomes/radiant-player-mac#342]
Keeps skipping songs and eventually says that Google Play can't be reached.

OS X 10.10.4

Radiant Player version 1.4.0.

**Comment by iuriaranda** [comment]
I started having the same issue yesterday.
OS X 10.10.4 and radiant player version 1.4.0

**Comment by dewet22** [comment]
Confirmed for me too. RP 1.4.0, OS X 10.10.3.

**Comment by saxofonbrian** [comment]
Me too. RP 1.4.0 - OS X 10.10.4
The music I uploaded to google myself, plays fine though.

**Comment by pardom** [comment]
The same problem exists in the Safari browser and I assume is the root of the problem.

**Comment by mbarany** [comment]
Same. Confirmed in Safari and filed a bug report with Google.

**Comment by edimitchel** [comment]
I think Yosemite 10.10.4 update is the source of this issue.

**Comment by pardom** [comment]
This was happening to me on 10.10.3. I updated to 10.10.4 and the issue persists.

**Comment by egyptianbman** [comment]
Same.  Tried toggling "HTML5 Audio" on and off to see if there was a difference and it's still failing to play radio.  I was playing around in the inspector in Safari and found that it is legitimately streaming the files so something else is keeping them from playing.

**Comment by rodneysbds** [comment]
I got a message today saying the Adobe Flash needed to be upgraded. I upgraded it, rebooted and now none of the selections are playing. Keeps skipping to the next song, but no sound. Removed/reinstalled Radiant Player, and same issue.

**Comment by aaronbwcollins** [comment]
works for me in chrome browser but not in radiant player. =[

**Comment by rockymountainhigh1943** [comment]
Experiencing the same issues here as well. On OS X 10.10.2 & Radiant Player version 1.4.0.

**Comment by gcarrion-gfrmedia** [comment]
I'm having the same problem too. Uploaded music plays fine. Google's Play Music won't play. New Radio Stations doesn't work neither.

**Comment by beauwilliams** [comment]
Same issue here w/ 10.10.4

**Comment by egyptianbman** [comment]
I was able to mimic much of the Radiant player functionality by just going to Google Play Music in Chrome and clicking the "pop out" button to open the mini player.  My main need is in being able to control the player with the MBP media keys. so this turns out to be perfect (and more lightweight since I don't need to load up Safari).
![image](https://cloud.githubusercontent.com/assets/323600/8632219/6efc54d0-2757-11e5-9af3-152f64503075.png)

**Comment by seltzered** [comment]
The problem seems to also occur in Firefox. Seems like music streaming only works in Chrome now.

**Comment by austinmw** [comment]
Same here with 10.10.4, tried reinstalling Radiant and Flash, but still can't reach Google Play.

**Comment by seltzered** [comment]
Note: I recommend everyone file a bug with google on this one. It's seems like Google's responsibility considering streaming doesn't work in other browsers.

<img width="411" alt="screen shot 2015-07-11 at 11 20 20 am" src="https://cloud.githubusercontent.com/assets/297435/8634857/04ffa254-27bf-11e5-9732-d768132b4107.png">

<img width="553" alt="screen shot 2015-07-11 at 11 20 56 am" src="https://cloud.githubusercontent.com/assets/297435/8634858/086fbfbe-27bf-11e5-8e59-5e2e1a082ab4.png">

**Comment by rodneysbds** [comment]
Well at least they are acknowledging the issue now. 

http://www.androidpolice.com/2015/07/11/google-play-music-all-access-web-app-is-not-working-in-firefox-internet-explorer-or-safari-on-desktops/

**Comment by jadengore** [comment]
Here's a copy of the thread going on at the Google Product Forums.

https://productforums.google.com/forum/#!topic/play/h_GVQu3iUzw;context-place=mydiscussions

**Comment by NoelLH** [comment]
Give it a try now. Looks like they've finally fixed it :)

**Comment by gbourassa** [comment]
I confirm, it's now working.

**Comment by tauil** [comment]
YES! Radiant back in business ftw!

**Comment by jadengore** [comment]
Working for me too, but I'm still getting some unusual skips. Could be exclusive to me though, and at least it's working now.

**Comment by edimitchel** [comment]
Like @jadengore, I'm still getting some unusual skips..

**Comment by jadengore** [comment]
@edimitchel Yeah, certain songs won't play. So far today it's been better, but I just noticed one right now that is skipping.

**Comment by rodneysbds** [comment]
Adobe just updated their flash plugin...again...and now Radiant Player stopped working, again.

**Comment by Tuinslak** [comment]
Is this flash related ?

**Comment by jadengore** [comment]
@sambass1 Maybe reopen the issue? Looks like there are still problems.

**Comment by sambass1** [comment]
Mine is working fine.

**Comment by tauil** [comment]
Eventually I'm getting unexpected skips too :disappointed:

**Comment by jadengore** [comment]
@sambass1 If you could please reopen this, it seems like people are still getting them.

**Comment by kbhomes** [comment]
The Flash Player issue seems to have sorted itself out, but some of you are still getting skipped songs. Can you determine whether the same is happening in Safari? Are they songs from All Access or uploaded songs?

**Comment by jadengore** [comment]
@kbhomes Last time I tested it was doing it in Safari. For me I've only been listening to All Access.

**Comment by Tuinslak** [comment]
I haven't had it in a while (or didn't notice it at least). But granted I've been listening to Soundcloud more the past week.

**Comment by kbhomes** [comment]
@jadengore Since audio is still being handled by Flash Player in Safari, it could be an issue that's also present in Firefox. Do you have Firefox available to see if it's present there as well?

**Comment by jadengore** [comment]
@kbhomes I do have Firefox. I'll test it out in there, but I think I have HTML5 Audio turned on...

**Comment by kbhomes** [comment]
@jadengore Radiant Player doesn't actually specify any configuration for HTML5 audio vs Flash Player. On Google Play Music, they locked down HTML5 audio to just Chrome. On Firefox, Safari, and other browsers, Flash Player is automatically used.

**Comment by jadengore** [comment]
Anyone else having any problems? I think mine are now gone for the most part...

**Comment by tauil** [comment]
Mine is working fine, right now.

**Comment by edimitchel** [comment]
Me too!


Cordialement,
*Michel EDIGHOFFER*
*Apprenti Ingénieur en Informatique*
www.micheledighoffer.fr

*Étudie l'informatique avec* l'*ITII Alsace* (CNAM Alsace) à *Eckbolsheim*
en alternance à la *CARSAT Alsace-Moselle*

2015-08-03 23:16 GMT+02:00 Rafael Borgonovi Tauil <notifications@github.com>
:

**Comment by jadengore** [comment]
Thanks @sambass1 for taking point on this issue! :+1:

**Comment by dmsabath** [comment]
Player stopped to play at the end of August.
No replies from owner.

**Comment by jadengore** [comment]
@dmsabath Did you check out #358 for a patched binary?

**Comment by dmsabath** [comment]
it helped
thanx a lot


чт, 1 окт. 2015 г. в 13:03, Edward Bramanti <notifications@github.com>:

**Comment by crquixote** [comment]
Anything new on this issue? I'm running Radiant 1.6.2 in El Captain and as the original posts states "Keeps skipping songs and eventually says that Google Play can't be reached."

**Comment by chrismou** [comment]
Hey @crquixote - do you have HTML5 Audio switched on, out of interest?  Go to settings (in the sidebar) then it'll be in the labs section

**Comment by crquixote** [comment]
Hey Chris,

Thanks for the quick reply. Turns out my problem had to do with an Internet plugin I had installed called 'click to flash'. I uninstalled the plugin and everything seems to be working fine. 
_____________
Regards,
Carlos R.
(973) 997-9950

🏄🌴🐠🏊☀

**Comment by chrismou** [comment]
:+1: Nice one, glad it's sorted. Thanks for letting us know!

**Comment by taip** [comment]
This has recently started happening for me every time I open Radiant. However I've noticed that if I open Google Music in Chrome, play a song, then quit and re-open Radiant, then Radiant is able to play just fine.

I don't have HTML5 Audio turned on, but the switch is disabled for some reason so I can't turn it on.
