### ISSUE TITLE
El Capitan Update

### ISSUE THREAD

**Issue by MrWalkman** [kbhomes/radiant-player-mac#343]
I know it's still time til El Capitan will be officially released, but Radiant Player isn't showing anything on El Capitan. Just an empty window.

Thanks!

**Comment by alksv** [comment]
The problem has nothing to do with Radiant Player, most probable culprit is Safari 9. It does work in i.e. Chrome, which has been verified. Please report this bug through Apple's Feedback Assistant.

**Comment by MrWalkman** [comment]
You are right. Google play music isn't opening in Safari. Funny! So Apple ist starting Apple Music and all of a sudden Google Music isn't working anymore in Safari...

**Comment by dtigue** [comment]
Same problem here. I would have thought this was an issue Google would have to work out. Haha, maybe Apple and Google will have to work together to find a solution. If that's the case it'll never get fixed. :+1:

**Comment by MrWalkman** [comment]
Even though I'm not even using flash with radiant player (don't have the subscription, just my own music so html5 is sufficient) some people are discovering that it has something to do with the click to flash feature in safari: http://forums.macrumors.com/threads/safari-google-play-music.1889009/

Any workaround for Radiant Player?

**Comment by alksv** [comment]
Confirmed working on El Capitan DP4.

**Comment by MrWalkman** [comment]
Can confirm Public Beta 2 as well

**Comment by fvcproductions** [comment]
I'm using El Capitan Public Beta 2 as well, and can confirm it works perfectly as well.

> If anyone is having problems where it keeps prompting you to install Adobe Flash Player, make sure to go to the **[other versions install page](https://get.adobe.com/flashplayer/otherversions/)**, and install the two different versions of `FP 18 for Mac OSX 10.6 - 10.10` (there are separate versions for `Safari`/`Firefox` and `Chrome`/`Opera`).
>
> I had to do this first in order to get it to work with a fresh install of El Capitan.

**Comment by kbhomes** [comment]
I'm going to close this issue and keep #344 as the current main issue on El Capitan problems, which appear to be centrally related to the mini player.
