### ISSUE TITLE
1.4.1 binary to address #351

### ISSUE THREAD

**Issue by jadengore** [kbhomes/radiant-player-mac#358]
@kbhomes Thank you for merging #352 to get #351 closed. When can end users expect a `1.4.1` binary to address the issues in #351 without having to download a patched older beta binary?

**Comment by rwoodpecker** [comment]
... In the meantime, it's very straightfoward to compile your own using xcode.

**Comment by jadengore** [comment]
@rwoodpecker Not everyone knows how to do that. I also tried to compile Radiant with Xcode and it didn't work for me. It would just be helpful to see that integrated for the end user's sake.

**Comment by rwoodpecker** [comment]
Definitely agree. I can upload a compile a binary of the latest code, if people are interested while we wait for @kbhomes to do release his own.

**Comment by gasperk** [comment]
@rwoodpecker please do.

**Comment by rwoodpecker** [comment]
@gasperk Give this a shot https://www.dropbox.com/s/fhep4abttrim1or/Radiant%20Player.zip?dl=1 Was compiled on Xcode 7 on El Capitan GM, fingers crossed it works.

**Comment by dan-delaney** [comment]
@rwoodpecker working for me on El Capitan.  Thanks.

**Comment by rlbaxter** [comment]
@rwoodpecker Working for me on Yosemite. Thank you for this.

**Comment by gasperk** [comment]
@rwoodpecker works for on Yosemite as well. Thanks!

**Comment by lauritz-it-operations** [comment]
Super! Was having the same problems. This build solved it!

**Comment by Teumer** [comment]
@rwoodpecker much appreciated, thank you

**Comment by nicolaspy** [comment]
@rwoodpecker Thank you! Worked for me on Yosemite!

**Comment by aloven** [comment]
@rwoodpecker Awesome work, thank you.

**Comment by EnderShadow** [comment]
@rwoodpecker Works for me as well. Thanks!

**Comment by spoulin** [comment]
HUrray to you.. it work again. Thanks!

**Comment by aaronbwcollins** [comment]
@rwoodpecker Thanks Man!

**Comment by dmsabath** [comment]
yaaaaaahoooooo
it works after 2 months of using ugly google chrome player

**Comment by jacobwgillespie** [comment]
In case anybody needs it ASAP, I've pushed an updated build with El Capitan support here: https://github.com/jacobwgillespie/radiant-player-mac/releases/tag/v1.4.0.  As before, as soon as @kbhomes gets 1.4.1 out, switch to that.  :)

**Comment by okvs** [comment]
Does anyone have any idea why it is taking so long to get out a new binary? It's a complete showstopper of a bug. It was reported a month and a half ago, and the fix was merged over three weeks ago. Is it a lot of work to get it out, or has this project been abandoned?

**Comment by jadengore** [comment]
I think developers who are interested in maintaining Radiant should consider moving the project into an organization, so we can get pull requests merged faster and make it easier to get distributed versions into the hands of end-users. @kbhomes has done great work, but we need more than one maintainer for an app with this much popularity.

**Comment by okvs** [comment]
I guess some sort of clarification from @kbhomes would be helpful. If he cannot keep working on this project then him saying so could get the ball rolling. Because of the radio silence, everyone is just going around saying that any day now, the new binary will be out, and things will be back to normal. That may not be the case.

This is a really great app, but right now it is completely broken. And for most casual users (me included), going to the github repo and reading through issues to seek out Dropbox links to unofficial builds is probably a bit off-putting.

**Comment by jadengore** [comment]
@okvs Most people would not know this unless you look through lists of issues. We need a group of maintainers in order to keep a constantly changing wrapper like this up-to-date.

**Comment by jadengore** [comment]
@kbhomes Thank you for finally fixing this issue, however I do think we need more discussion about adding other collaborators to this project to address issues quickly. Closing for now.

**Comment by spoulin** [comment]
I don't know if it's only me, but now I can't authorize my last.fm user.

**Comment by chrismou** [comment]
@spoulin No, same. Not scrobbling, so deauthorized and now it won't let me authorize again.

Am going to go through the old issues and see if any of the compiled versions linked to from dropbox are working.
