### ISSUE TITLE
Music not playing, strange white rectangle in bottom-left

### ISSUE THREAD

**Issue by rlbaxter** [kbhomes/radiant-player-mac#360]
I am running OSX 10.10.5 and I have flash installed. I have Radiant Player version 1.4.0. When I open the app I get a weird white rectangle in the bottom left. I can interact with the app, selecting songs, albums, or radio stations, but no audio plays when I click play. See screen shot.

Also I have opened the google web app in the latest version of chrome and safari and I do don't experience the same problems there.
![screen shot 2015-09-17 at 9 28 32 am](https://cloud.githubusercontent.com/assets/2219637/9937870/dc348592-5d1f-11e5-8d8c-e24ab582340e.png)

**Comment by rlbaxter** [comment]
Did some more research and found issue #318 but I'm on the latest version of everything and still having the issue. Here is the console output: https://gist.github.com/rlbaxter/a7c9c9469c98bc031b71

**Comment by abrammer** [comment]
Isn't this the same as #351 and #352 and #358 ?  There is a compiled version linked in #358.  Otherwise I think the solution for now is to build it yourself from the source code.

**Comment by rlbaxter** [comment]
Indeed it is. Thanks. Didn't see those in my search, I apologize for creating duplicates.
