### ISSUE TITLE
Fresh install will not play.

### ISSUE THREAD

**Issue by chamunks** [kbhomes/radiant-player-mac#362]
# Will not play just sits and spins.
![http://i.imgur.com/EjKHVnx.png](http://i.imgur.com/EjKHVnx.png)

## Screenshots of versions of relevant things.
This includes a screenshot showing RadiantPlayer failing to play and its version along with Yosemite and its version and Safari and its version.
![http://i.imgur.com/AvtQx6P.png](http://i.imgur.com/AvtQx6P.png)

If you need any more information please let me know and I can paste it.

**Comment by chamunks** [comment]
Also note the strange white box in the first screenshot its not some strange method of me censoring something its just floating there.

**Comment by italobarboza** [comment]
Same problem here.
![captura de tela 2015-09-22 22 20 33](https://cloud.githubusercontent.com/assets/1903833/10036070/33ab3170-6178-11e5-854e-ba0713cd6501.png)

**Comment by PIONNIER** [comment]
Same here. Floating white box and not playing.

**Comment by TheGorlie** [comment]
Same here with OS X Yosemite 10.10.5.

**Comment by justiceamoh** [comment]
Same here, OS X Yosemite 10.10.5

**Comment by ericnorris** [comment]
@chamunks, seems like that is probably due to #351. You'll either have to wait for @kbhomes to close #358 and/or release a new binary including the fix, or build it yourself from source (or trust someone else's build).

**Comment by justiceamoh** [comment]
@ericnorris, you're right. thanks! I used the binary from @jacobwgillespie on #351 and that works fine. It's been merged in #358 so I guess compiling from that source should work too.

**Comment by chamunks** [comment]
Yes I can confirm that one of the downloads from #351 linked works.  I am so happy to finally ditch having to run a browser 24/7 just to listen to music.  I really hope this gets merged asap.

**Comment by cbass717** [comment]
I have the same exact issues on both 10.11 and 10.11.1. I have uninstalled and reinstalled both Flash and Radiant Player, but nothing seems to fix these issues.

**Comment by chamunks** [comment]
Just switch to a fork thats maintained really.

**Comment by jacobwgillespie** [comment]
Fixes for this and for El Capitan have landed in master but haven't been released yet.  I've pushed an update of my 1.4.0 build with the fixes to https://github.com/jacobwgillespie/radiant-player-mac/releases/tag/v1.4.0 if you're interested.  As before, update to 1.4.1 once it's out.  :)

**Comment by cbass717** [comment]
Thanks for the help guys, Jacob I used your build and it works great. Good to be using this app again. Cheers.

**Comment by jacobwgillespie** [comment]
1.4.1 has been released and should fix this issue - @chamunks, can you check and close if it's working?

**Comment by chamunks** [comment]
Confirmed for me yes, it also works as promised on El Capitan.
