### ISSUE TITLE
any update before elcap?

### ISSUE THREAD

**Issue by jywll** [kbhomes/radiant-player-mac#363]
crashes on launch.
Thanks

**Comment by jacobwgillespie** [comment]
It's been fixed in master - if you need a temporary build until 1.4.1 is out, you can build yourself or I built a copy of 1.4.0 with the fixes at https://github.com/jacobwgillespie/radiant-player-mac/releases/tag/v1.4.0 that I'm using (though definitely update to 1.4.1 after it comes out).

**Comment by jywll** [comment]
far out. Yes, your version works. Will grab the new version when available. 
Thanks for that
